### PR TITLE
Add note about clang-format versions

### PR DESCRIPTION
**Pull request by michael-okeefe**
After struggling with this, just wanted to pass along this hard-earned information for others.

## Description

Updates README to hopefully save others pain in setting up clang-format for their projects.

## Reviewer Checklist:

 - [ ] Read the pull request description
 - [ ] Perform a code review on GitHub
 - [ ] Confirm all CI checks pass and there are no build warnings
 - [ ] Pull, build, and run automated tests locally
 - [ ] Perform manual tests of the fix or feature locally
 - [ ] Add any review comments, if applicable
 - [ ] Submit review in GitHub as either
     - [ ] Request changes, or
     - [ ] Approve
 - [ ] Iterate with author until all changes are approved
 - [ ] If you are the last reviewer to approve, merge the pull request and delete the branch

### CODE REVIEW

**Review by tanaya-mankad — COMMENTED** [review]
Actually, some details about clang-format versions are spelled out in detail in the guidelines.md document already, as I ran into similar issues! The directives in our clang-format file are compatible with 16.  @michael-okeefe could you have a look under "Editor Settings" there and then we can consolidate our observations in the readme?

**Comment by michael-okeefe** [comment]
Thanks, @tanaya-mankad ! Didn't actually know there was already discussion on this in the `guidelines.md` -- apologies for missing that.

I think the main issue was I hadn't seen guidelines and had installed clang-format 18 and couldn't figure out why things weren't working for me until I realized that even if you specify the clang-format version in your .clang-format file, it matters what version of the clang-format engine is doing the formatting and checking the formatting on the CI -- apparently since those versions were different there was slight differences in formatting behavior which caused the CI to fail. I'm not sure if that extra information needs to be added to the guidelines file or not as, had I actually followed your instructions, I wouldn't have had an issue ;-)

**Comment by tanaya-mankad** [comment]
Let's move that critical info to the readme then! It's undoubtedly the right place for install dependencies. I'll make that change.

**Comment by michael-okeefe** [comment]
Shall I delete this PR at this point?

**Comment by uncommoner** [comment]
Sorry, i think it just got missed? I'll check today!

**Review by tanaya-mankad — CHANGES_REQUESTED** [review]
If you re-spell "you're" I'll merge this. ;)

**Comment by michael-okeefe** [comment]
Done, thanks!

**Review by tanaya-mankad — APPROVED** [review]

**Pull request merged**
